### ISSUE TITLE
64 bit MSVC warnings

### ISSUE THREAD

**Issue by paulsapps** [ebiggers/libdeflate#11]
```
Warning	3	warning C4267: 'function' : conversion from 'size_t' to 'uint32_t', possible loss of data	F:\Data\alive\alive\3rdParty\libdeflate\common\common_defs.h	289
Warning	4	warning C4267: 'function' : conversion from 'size_t' to 'uint32_t', possible loss of data	F:\Data\alive\alive\3rdParty\libdeflate\common\common_defs.h	331
Warning	5	warning C4267: 'function' : conversion from 'size_t' to 'u32', possible loss of data	f:\data\alive\alive\3rdparty\libdeflate\lib\unaligned.h	159
Warning	1	warning C4244: 'return' : conversion from 'uint64_t' to 'unsigned int', possible loss of data	f:\data\alive\alive\3rdparty\libdeflate\common\compiler_msc.h	85
Warning	2	warning C4244: 'return' : conversion from 'uint64_t' to 'unsigned int', possible loss of data	f:\data\alive\alive\3rdparty\libdeflate\common\compiler_msc.h	93
Warning	6	warning C4018: '>=' : signed/unsigned mismatch	f:\data\alive\alive\3rdparty\libdeflate\lib\decompress_impl.h	277
```

Even when _M_X64 is defined

**Comment by ebiggers** [comment]
I think it is probably not worthwhile to "fix" a list of unhelpful warnings each time someone decides to use a new compiler or enable different warnings.

**Comment by paulsapps** [comment]
Level 4 warnings in MSVC is quite well defined across versions. So the truncation of 32bits of data isn't a problem in this case?

**Comment by ebiggers** [comment]
No.  None of these is a real bug, and in none of these cases would it be an improvement, in my opinion, to add a cast to work around the warning.  In some cases, attempting to "silence" compulsive compiler warnings can cause or hide real bugs.

I would take the report more seriously if you were using the recommended compiler (GCC) with the recommended compiler flags or if these warnings were on by default (they're not; I have compiled the code with MSVC and encountered no warnings).

For now I am closing this issue.

**Comment by paulsapps** [comment]
Default MSVC projects use LVL3 warnings is why you won't see any :). Seems strange to recommend only 1 compiler for a lib though. Ideally should be compatibility with as many as possible. My project uses gcc clang and msvc on the highest warning levels. Unless you mean gcc has had the most testing.

**Comment by ebiggers** [comment]
The source code is _compatible_ with all three compilers you named.  GCC is _recommended_ because it is cross-platform (especially, not tied to the software ecosystem of a particular vendor), produces better-performing binaries, and has been better tested for this code.

Compiler warnings do not have much to do with compatibility, as they are not standardized and are purely advisory.  You can have as few of them or as many of them as you want.  If I compile libdeflate with clang's `-Weverything`, there are 107 warnings emitted.  Would it really be worthwhile to make source code changes to work around them?  I am much more interested in whether the code has the correct behavior --- not merely whether it satisfies certain stylistic constraints.  So I would rather spend time on more effective measures.
