### ISSUE TITLE
Example of use of libdeflate_zlib_decompress or deflate_decompress?

### ISSUE THREAD

**Issue by benkasminbullock** [ebiggers/libdeflate#116]
Is there an example of the use of `libdeflate_zlib_decompress` or `deflate_decompress`? I'm not at all sure what is supposed to happen when we don't know the size of the output buffer. The example in `programs/benchmark.c` uses the `original_size`, the example in `programs/gzip.c` uses the size field in the `gzip` buffer. I don't see anywhere where there is an example of what to do about decompressing an unknown-sized thing.

**Comment by ebiggers** [comment]
Not knowing the output size is discouraged, because this makes things a lot less efficient and invites denial of service attacks.  A properly designed protocol, file format, or application will store and validate the uncompressed size separately from the compressed data.

If you do need to decompress without knowing the output size at all, you'll have to make a guess, and keep retrying decompression with a larger buffer until you stop seeing `LIBDEFLATE_INSUFFICIENT_SPACE`.

**Comment by benkasminbullock** [comment]
OK thank you.
