### ISSUE TITLE
Libdeflate vs ECT

### ISSUE THREAD

**Issue by lorents17** [ebiggers/libdeflate#12]
File: enwik8, 100,000,000 bytes, compressed into gzip format

|Compressor|File Size|Time|
|----------|----------|----------|
|gzip -12|35 100 553 byte|22.608s|
|ect -2|35 350 269 byte|23.478s|
|ect -3|35 013 879 byte|30.082s|
|ect -4|34 967 607 byte|35.125s|

Tell me, it is planned to increase compression level?

**Comment by ebiggers** [comment]
Maybe.  It is very difficult to make improvements at this level because the result is already so close to optimal.

In the case of enwik8 specifically, the main problem libdeflate at its strongest level currently has is that it is still creating too many blocks, even after the new block splitting algorithm.  If you temporarily change the expression `250 * stats->num_observations` in deflate_compress.c to `500 * stats->num_observations`, then libdeflate gzip -12 compresses enwik8 to 35,008,205 bytes, beating `ect -3`.  But that is not an advantageous change in general --- just for enwik8 specifically.  The algorithm needs to do well for a variety of inputs, not just certain common benchmarks.

**Comment by lorents17** [comment]
|Compressor|File Size|Time|
|----------|----------|----------|
|gzip -12|35 008 205 byte|21.648s|

It is possible to use algorithm of Zopfli for search of optimum number of blocks?

**Comment by fhanau** [comment]
The blocksplitting of ECT -3 takes about 6 seconds, zopfli's takes even more time at very slightly better quality, so that would reduce the speed advantage.

**Comment by lorents17** [comment]
Tell me, do you plan to improve the block splitting algorithm?

**Comment by lorents17** [comment]
File: enwik8, 100,000,000 bytes, compressed into gzip format

|Compressor|File Size|Time|
|----------|----------|----------|
|gzip -12|35 100 586 byte|21.105s|
|ect -2|35 329 716 byte|24.888s|
|ect -3|35 012 496 byte|27.208s|
|ect -4|34 967 607 byte|31.585s|

**Comment by lorents17** [comment]
Tell me how to improve the compression ratio to level ect -3?
