### ISSUE TITLE
Test file integrity option

### ISSUE THREAD

**Issue by tansy** [ebiggers/libdeflate#125]
I noticed that gzip doesn't have option for testing file integrity so I have done one. It's not pull request, but diff ready for patching. It may not be very you would do that but have a look and consider to add the option as it's extremely useful and simple to implement in the same time.

Reason of this request is that libdeflate is definitely fastest implementation of all known to me and when it comes to checking of big amount of gzip compressed data it is my favourite but sending it to /dev/null is diminishing benefits.

I attach diff file to the post.

[libdeflate-1_7-testa_diff.GZ](https://github.com/ebiggers/libdeflate/files/6144975/libdeflate-1_7-testa_diff.GZ)

**Comment by ebiggers** [comment]
At first glance, this seems reasonable to support.  GNU gzip and gunzip has this option too, and it doesn't appear to require any changes to the library.  (It would be faster with library support, but it doesn't require it; just avoiding writing the data to a file descriptor is still a benefit.)

Can you open this as a pull request so that it can be properly reviewed?

**Comment by tansy** [comment]
Sure, I'll try. I'm not fan of git as I don't know it. That's why I attached diff patch. Give me few days, I have to find time.
