### ISSUE TITLE
What are the "file access hints and more precise timestamps" features cited in 1.4 release notes?

### ISSUE THREAD

**Issue by JoeUX** [ebiggers/libdeflate#126]
The release notes for 1.4 say: "Fixed a bug where support for certain optimizations and optional features (file access hints and more precise timestamps) was incorrectly omitted when libdeflate was compiled with -Werror."

I can't find any other reference to these features, and they're not in `gzip -h`. What are they, and how do we use them?

**Comment by ebiggers** [comment]
"file access hints" refers to the "I am going to access this file sequentially" hint that `libdeflate-gzip` gives to the operating system when opening files, using the `posix_fadvise()` or `posix_madvise()` C library functions.  This is only an optimization and doesn't affect behavior.

"more precise timestamps" refers to `libdeflate-gzip` using the `futimens()` or `futimes()` C library functions to preserve timestamps with nanosecond precision instead of using the more portable `utime()` C library  function to preserve them with second precision only.

These are optional for the build, not for the user.  The build will use whatever functions are supported on the operating system.  The bug fixed in v1.4 was that sometimes builds of libdeflate did not use these functions when the operating system supported them.  So, for example, if you used `libdeflate-gzip` to compress a file (or `libdeflate-gunzip` to decompress a file), the timestamp on the file might be rounded down to the nearest second rather than preserved exactly as would be expected.
