### ISSUE TITLE
Release for Ubuntu 18.04 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by JoakimJoensuu** [ebiggers/libdeflate#132]
Is there any plans for creating a release for Bionic Beaver?

All the other latest Ubuntu releases has their own release
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libdeflate-dev&searchon=names

**Comment by ebiggers** [comment]
Upstream libdeflate isn't responsible for Ubuntu packages.  You need to file an Ubuntu bug for this.

I don't believe that Ubuntu generally adds new packages to already-released Ubuntu versions, though.  So you may not have much luck.  Maybe try to get it added to `bionic-backports` rather than `bionic`?

Regardless, you can still compile libdeflate from source yourself.
