### ISSUE TITLE
Question, compatibility with alternative zlib implementations?

### ISSUE THREAD

**Issue by PhantomG27249** [ebiggers/libdeflate#136]
Just wondering if this might be compatible with alternative zlib and gzip implementations such as cloudflare or zlib-ng given that zlib and gzip are wrappers for the deflate stream.  Cause it would be really cool to be able to use this with one of the optimized zlib/gzip implementations/wrappers.

**Comment by ebiggers** [comment]
libdeflate uses the same data formats (DEFLATE, zlib, and gzip), so you can compress data with libdeflate and decompress it with other software that supports these formats, or alternatively compress with other software and decompress with libdeflate.  However, the API isn't compatible.  So e.g. if you have a program using the zlib library, you can't drop-in libdeflate as a replacement without changing the program's code to use libdeflate's API instead of zlib's API.

**Comment by PhantomG27249** [comment]
thank you for the response, cheers :)
