### ISSUE TITLE
OOM error on decompression with corrupted input file

### ISSUE THREAD

**Issue by Guilucand** [ebiggers/libdeflate#157]
Hi,
I found a bug in the decompression routine, that does not recognize an input file as corrupted, and instead tries to continuously decompress it until oom.

The cause is that the main deflate decode loop does not respect the assumption of the FILL_BITS_BYTEWISE macro that the decompressor always make forward progress, and that puts the algorithm in a state where it continuously copies the same data to the output buffer.

A workaround i found is to put a condition on the overrun_count variable on the decode loop, to ensure that if it gets too large the loop ends and the error can be catched by the ALIGN_INPUT macro.
If it seems reasonable as a fix, I can make a pull request.

Here there is the file that causes this problem:
[corrupted.fasta.gz](https://github.com/ebiggers/libdeflate/files/7872161/corrupted.fasta.gz)

**Comment by ebiggers** [comment]
Well, from the library's perspective this was sort of intentional; see the comment [here](https://github.com/ebiggers/libdeflate/blob/v1.9/lib/deflate_decompress.c#L202).  Since libdeflate is buffer-based, producing output was assumed to count as forward progress, since the output buffer will eventually fill up.  The problem only arises when decompressing with an unknown output size, which requires wrapping decompression with a retry loop that allocates increasingly large buffers.  This is not the recommended usage, but this is what `libdeflate-gunzip` has to do, since gzip is a bad file format.

I'll see what I can do to make things better.  Of course, nothing is going to change the fact that a very small compressed file can decompress to a huge amount of data; that's an intrinsic property of data compression.

**Comment by ebiggers** [comment]
I've submitted changes that address this.  Thanks!
