### ISSUE TITLE
Missing options for gzip wrappers

### ISSUE THREAD

**Issue by jamigo** [ebiggers/libdeflate#169]
OS's **gzip** wrappers require some options which these gzip and gunzip executables don't have. In particular, **zgrep** complains as this gzip doesn't have the **-q** (quiet) option, and **zcat -f** complains as this gzip doesn't allow non gzipped streams to passthough (OS's zcat behaves as cat from uncompressed streams if the **-f** option is used). Is there any way to make this 2 commands, and any other OS's gzip wrappers, work with these gzip and gunzip executables?

**Comment by ebiggers** [comment]
I think it would be reasonable to add these options.  `libdeflate-gzip` and `libdeflate-gunzip` aren't intended to be a complete replacement for the standard programs, especially since libdeflate doesn't support streaming, but these options look relatively straightforward to add.  `-f` is already supported, but it sounds like it's incomplete.

**Comment by ebiggers** [comment]
This was implemented by https://github.com/ebiggers/libdeflate/pull/172.
