### ISSUE TITLE
how to change  sliding window size  at runtime?

### ISSUE THREAD

**Issue by sxstd001** [ebiggers/libdeflate#349]
how to change  sliding window size  at runtime?

**Comment by ebiggers** [comment]
libdeflate's compressor always uses a sliding window size of 32 KiB.  There's been very little demand for smaller sizes because 32 KiB is already small by modern standards.  More modern compression formats typically use megabytes.

Note, the decompressor supports all DEFLATE compressed data, regardless of which sliding window size the compressor used.
