### ISSUE TITLE
build with GCC13 on NetBSD failed due to Error: unsupported instruction `vpdpbusd'

### ISSUE THREAD

**Issue by leleliu008** [ebiggers/libdeflate#387]
details please see https://github.com/leleliu008/test/actions/runs/10511472981/job/29122507907

**Comment by ebiggers** [comment]
The problem is that the gcc13 package in NetBSD (`/usr/pkg/gcc13/bin/gcc`) is configured to use the "system" assembler (`/usr/bin/as`) which is from binutils 2.34, instead of the "pkgsrc" assembler (/`usr/pkg/bin/gas`) which is from binutils 2.41.

When gcc is upgraded, the binutils it uses needs to be upgraded alongside it.  Otherwise, not all instructions the compiler generates can be assembled.

I recommend that you report the misconfigured `gcc13` to the maintainer of that package in NetBSD, and for now do the build with the NetBSD's "system" gcc (`/usr/bin/gcc`) which is gcc 10 and is properly paired with the binutils 2.34.

The only workaround that libdeflate could do is detect broken toolchains in the CMakeLists.txt and disable optimized code accordingly.  Performance would decrease, and this workaround would not work for anyone using another build system.  I would prefer that people fix their toolchains instead, as that is the real problem.

**Comment by ebiggers** [comment]
Here is the line that sets the assembler incorrectly when the `gcc13` package is being built: https://github.com/NetBSD/pkgsrc/blob/trunk/lang/gcc13/Makefile.common#L90

**Comment by leleliu008** [comment]
@ebiggers Thank you for your reply. I will try to use `/usr/pkg/bin/gas`

**Comment by leleliu008** [comment]
This works for me:

```bash
sudo pkgin -y install gcc13 binutils cmake gmake

sudo ln -sf /usr/pkg/bin/gas /usr/bin/as

export  CC='/usr/pkg/gcc13/bin/gcc'
export CXX='/usr/pkg/gcc13/bin/g++'

cmake \
    -S . \
    -B build.d \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DCMAKE_COLOR_MAKEFILE=ON \
    -DCMAKE_INSTALL_PREFIX=$PWD/out \
    -DCMAKE_BUILD_TYPE=Release
cmake --build build.d
cmake --install build.d
```

**Comment by ebiggers** [comment]
Can you check if https://github.com/ebiggers/libdeflate/pull/389 allows libdeflate to build with gcc 13 on NetBSD without having to run `sudo ln -sf /usr/pkg/bin/gas /usr/bin/as`?  The proper solution is still to get the gcc 13 NetBSD package fixed, but https://github.com/ebiggers/libdeflate/pull/389 should allow libdeflate to build regardless by disabling some optimized code that can't be assembled.

**Comment by leleliu008** [comment]
@ebiggers It works. I test it with github actions: https://github.com/leleliu008/test/actions/runs/10642405602
