### ISSUE TITLE
Writes corrupt files when compressed data > 4GB

### ISSUE THREAD

**Issue by GabeAl** [ebiggers/libdeflate#44]
Hi,

Just wanted to point out the gzip program produces truncated files for all writes that should be >4GB. 

I imagine this should be a trivial fix (maybe define the file offset bits = 64, or fix some assumption of 32-bit file pointers?). 

Ubuntu 18.04 WSL

**Comment by ebiggers** [comment]
Thanks, I pushed out a fix for this.  There was indeed a variable being incorrectly truncated to 32 bits.

Note, however that libdeflate doesn't implement streaming, so its gzip program needs 8 GiB of memory to compress a 4 GiB file.  Needless to say, that's not really recommended to do.  (And people don't seem to be using libdeflate in that way, as otherwise this bug would have been reported long ago.)

**Comment by GabeAl** [comment]
Awesome. 

I've noticed the RAM use, but my system has terabytes of RAM (I'm that kind of nerd), so I'm happy with the speed and compression advantages, even compressing a number of 100GB files in parallel. 

If RAM is the only cost for this kind of performance (speed and ratio while remaining gzip compatible), I'll happily pay it. Curious what it would take to implement streaming, although you mentioned in the readme it would ruin the code with complexity, and libdeflate was built for a different use in mind.

Cheerio,
Gabe

**Comment by ebiggers** [comment]
Sure, if you have enough memory it will work.  Decompression speed won't be optimal for files over 4 GB, since libdeflate's `gunzip` may have to restart the decompression a few times with a larger output buffer.  But even with that it may still be faster than regular `gunzip`.

I don't plan to add true streaming support to libdeflate, but what I probably should do is make libdeflate's `gzip` create multi-member gzip files.  That wouldn't be too hard, and it would limit the memory usage of `gzip` and `gunzip` to some not-totally-insane value like 128 MB without affecting the compression ratio  much.
