### ISSUE TITLE
Target attribute unsupported on lots of compilers

### ISSUE THREAD

**Issue by nemequ** [ebiggers/libdeflate#5]
I just tried to pull the latest changes into Squash so I could enable AppVeyor (MSVC) builds for libdeflate, and it ended up triggering [several issues on Travis](https://travis-ci.org/quixdb/squash/builds/105969076).  If you think it would be appropriate to ignore the warnings I could always pass -Wno-unknown-attributes, but it would probably be better to fix them…

I'm not sure what, exactly, is going on with OS X, but I think it's related.  Those errors don't happen with 6e5ef3ea.

**Comment by nemequ** [comment]
FWIW, I'd be willing to help set up a similar Travis configuration for you.  Squash's is a bit complicated since it has to deal with CMake's BS, Coverity, Coveralls, etc., but porting [µnit](https://github.com/nemequ/munit/)'s would probably be pretty straightforward.

**Comment by ebiggers** [comment]
Thanks for the report.  I don't usually test so many different compiler versions!  I'm interested in a Travis configuration; I'll look into it.

I've added in compiler version checks which should resolve the main problem with `__attribute__((target))` not being supported on some compiler versions.

However, the case with GCC 5 on Mac is different because the compiler supported `__attribute__((target("bmi2")))`, but then the assembler was unable to assemble BMI2 instructions.  That seems like a toolchain misconfiguration.  Does the system have a recent binutils installed alongside GCC 5, or it is using the assembler, linker, etc. that come with XCode?

**Comment by nemequ** [comment]
> Does the system have a recent binutils installed alongside GCC 5, or it is using the assembler, linker, etc. that come with XCode?

I'm not sure what version it was, but I added a command to install the latest version of binutils in homebrew (2.25.1) and [it didn't seem to make a difference](https://travis-ci.org/quixdb/squash/jobs/105992399)

**Comment by ebiggers** [comment]
Well, I don't personally have a Mac available to test any of this on, but I hear that GNU binutils isn't supported on Mac and instead you need to use either the system assembler (which is clearly out-of-date) or the clang integrated assembler (which may be more up to date).  "-Wa,-q" can supposedly be added to the GCC compiler flags to cause the clang integrated assembler to be used instead.  I don't know if this means clang needs to be installed separately as well or if it already comes with XCode.  Can you try adding that flag to the build jobs on Mac?

Note that the 'target' attribute support was a separate issue and should be resolved by the version checks I added, so you should also try re-running the other jobs.

**Comment by nemequ** [comment]
-Wa,-q does seem to help: https://travis-ci.org/quixdb/squash/builds/106354439

The 64-bit mingw build being broken is interesting.  Seems like OS X has a similar issue now that it managed to get past the assembly thing.  Assuming you're on Linux, that should be much easier to test than OS X…

**Comment by nemequ** [comment]
https://travis-ci.org/quixdb/squash/builds/106367922 contains a better version.  I changed it so -Wa,-q is only used for GCC (it causes an error with clang), which got clang a bit further; it now complains about the target attribute being missing :/

**Comment by ebiggers** [comment]
The undefined symbol errors will be fixed if you add x86_cpu_features.c to the files being compiled.  It can just be added unconditionally, since the contents are automatically #ifdefed out when not needed.

Perhaps you may find it easier to have your build system call the provided Makefile?  It seems you must run into link-time errors whenever people add, rename, or remove source code files.

I don't yet know why the version detection for clang didn't work on Mac.  Is there any way you can compile the following program with that clang version and post its output?:

```
#include <stdio.h>

int main()
{
        printf("%d.%d\n", __clang_major__, __clang_minor__);
}
```

**Comment by ebiggers** [comment]
Apparently, Apple numbers their clang versions differently for some reason.

clang has a __has_attribute() macro that I should be able to use instead, however.

**Comment by nemequ** [comment]
> Perhaps you may find it easier to have your build system call the provided Makefile? It seems you must run into link-time errors whenever people add, rename, or remove source code files.

No, unfortunately that really messes things like VS project files, alternatives to make (some people really like ninja because it's faster than make).  It's not much of an issue because I usually assume that if pulling in a new version makes it stop working the first thing I should do is check for new files.  With all the other problems, though, I blamed libdeflate first; sorry.

I'll fire off another build as soon as you fix the clang thing.

On an unrelated note, https://graphics.stanford.edu/~seander/bithacks.html has portable versions of some of the platform/compiler-specific functions you use; it should be possible to provide a portable fallback…

**Comment by ebiggers** [comment]
Thanks, I've pushed a commit that should fix the clang version detection.

libdeflate actually already has fallbacks for the "trivial" things like byte swaps.  The target function attribute is used for something a little more significant: compiling entire functions with different target instruction sets.  The fastest one is then chosen at runtime.  Of course, care needs to be taken to only turn this on when supported by the compiler, as you've noticed.

**Comment by nemequ** [comment]
Okay, the latest result is at https://travis-ci.org/quixdb/squash/builds/106390950

As you can see, GCC gets `-Wa,-q`, and it works for the debug build but not the release build.  The only real difference between the two is the CFLAGS; for debug they are `-g -O2`, and for releases `-DNDEBUG -O3 -flto` (see https://github.com/quixdb/squash/blob/master/CMakeLists.txt#L144).

**Comment by ebiggers** [comment]
I bet it is running into this bug:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47785

Since -flto was given, gcc is doing link-time optimization, and it doesn't pass the -q option to the assembler at that time.

I'm not sure how I can reliably work around this on my side without adding something like a configure script.  It's largely a toolchain problem: not only can the compiler produce instructions which the assembler cannot assemble, but there is no way to pass options to the assembler when link-time optimization is being used.

Possiblities for you are:
* Don't use -flto when compiling libdeflate with GCC 5 on Mac
* or, add -DRUNTIME_CPU_DETECTION=no when compiling libdeflate with GCC 5 on Mac

**Comment by nemequ** [comment]
I added -fno-lto to the cflags for the libdeflate plugin for OS X with GCC, and everything seems to work.

You're right that it's really a toolchain problem, but my understanding is that homebrew is pretty much the de dacto standard for OS X, at least if you're not using xcode, so it's probably worthwhile to support it.  Luckily LTO is less common; LTO with GCC on OS X should be relatively uncommon.  Hopefully I'll be able to remove the -fno-lto flag at some point…
