### ISSUE TITLE
wrong detection of AVX512

### ISSUE THREAD

**Issue by inikep** [ebiggers/libdeflate#56]
adler32.c compilation fails on Ubuntu 14.04 but not on 16.04 with the same `gcc-5` version:
https://travis-ci.org/inikep/lzbench/jobs/602079354
```
gcc-5  -Wno-unknown-pragmas -Wno-sign-compare -Wno-conversion -fomit-frame-pointer -fstrict-aliasing -ffast-math -O3 -DNDEBUG libdeflate/adler32.c -std=c99 -c -o libdeflate/adler32.o
/tmp/ccM6MhGs.s: Assembler messages:
/tmp/ccM6MhGs.s:428: Error: operand type mismatch for `vpmaddubsw'
/tmp/ccM6MhGs.s:429: Error: operand type mismatch for `vpsadbw'
/tmp/ccM6MhGs.s:431: Error: operand type mismatch for `vpmaddwd'
```

Probable reason is `Some platforms support AVX512F but not AVX512BW`:
https://github.com/microsoft/onnxruntime/pull/2083

**Comment by ebiggers** [comment]
(Sorry for the slow response.)

> Probable reason is Some platforms support AVX512F but not AVX512BW:

That doesn't seem to be the problem, since the code checks for AVX-512BW support.

The problem seems to be that you paired a newer version of gcc, which supports AVX-512BW, with an older version of binutils which does not.  (The errors came from the assembler, not gcc.)

It's not possible to work around this in the source code, as the source code can only check for compiler support, not assembler support.  Assembler support could be checked in a build script, but not everyone uses the provided build system.

So given that it's mainly the user's responsibility to provide a working toolchain, Ubuntu 14.04 reached end-of-life 8 months ago, and gcc-5 wasn't its default gcc anyway, I'm not sure there's anything I should do here.  I could bump up the gcc requirement, e.g. don't enable AVX-512 unless gcc is version 7 or later, but that wouldn't directly solve the problem as an old binutils could still be used with gcc 7+, or someone could use new binutils with gcc 5 or 6 and expect the AVX-512 support to work.

**Comment by ebiggers** [comment]
As per the above, I think working around broken toolchains is outside the scope of libdeflate when it can't be done in the C source code.  So I'm closing this.
