### ISSUE TITLE
Don't depend on undefined behavior

### ISSUE THREAD

**Issue by nemequ** [ebiggers/libdeflate#7]
Unaligned access is undefined behavior, and not necessarily safe even with GCC on x86.  For example, LZ4 had a problem recently with GCC 4.9 adding a new optimization which vectorized an operation, and the new instruction didn't support unaligned access (a lot of the vector extensions don't), which was causing crashes.  wfLZ is still having [a similar problem](https://github.com/ShaneWF/wflz/issues/4).  http://fastcompression.blogspot.fr/2015/08/accessing-unaligned-memory.html has some interesting information.

**Comment by ebiggers** [comment]
Thanks for the heads-up.  Fortunately, I am aware of the various hazards of undefined behavior, including unaligned memory accesses.  Currently, unaligned memory accesses are, when selected for the target architecture, done via a struct declared with `__attribute__((packed))` (for gcc-like compilers), or via `memcpy()` (for any other compiler, including Visual Studio).  Under no circumstances is a misaligned pointer dereferenced directly.

I have also tested libdeflate on ARM and MIPS, and on x86 with UBSan.

I see that you test other squash codecs with UBSan: https://github.com/quixdb/squash/issues/93.  Was there a specific issue that came up with libdeflate or was this just advisory?

**Comment by nemequ** [comment]
I saw the `UNALIGNED_ACCESS_IS_FAST` define, and that there was no way to override that behavior.  Of all the codecs I've seen, libdeflate is the first to have a define like that but still avoid unaligned accesses; everyone else who has something like that just uses it to switch between memcpy and dereferencing a pointer to an unaligned value and assuming it will work because they think x86 supports unaligned access.

FWIW, MSVC [does support packed structs](https://msdn.microsoft.com/en-us/library/2e70t5y1.aspx).  I have no idea how performance compares with memcpy, though, and memcpy is the portable way to do it.

**Comment by ebiggers** [comment]
`memcpy()` generates the desired code with MSVC on x86 and x86_64, although I have not tested older versions of that particular compiler.  I still use `__attribute__((packed))` with gcc and clang mainly out of habit but also because of the known issue with ARMv7, which supposedly will be fixed in gcc 6.

It may be a good idea to provide a way to override `UNALIGNED_ACCESS_IS_FAST` without editing the compiler.h file.  I generally prefer having the best settings detected automatically, however --- and if they aren't the best settings, then the detection code should be updated rather than adding a build-time override.
