### ISSUE TITLE
deflate_compress: Significant performance drop + increase in ratio compared to zlib on levels 8 and 9 with some data

### ISSUE THREAD

**Issue by dktapps** [ebiggers/libdeflate#85]
I'm currently working on a PHP binding for libdeflate.

I'm compressing the following file using zlib vs libdeflate: https://github.com/pmmp/BedrockData/blob/afc885cccae38048d309911f2c5ddcdcb6af8152/required_block_states.nbt

From levels 1 to 7, zlib and libdeflate achieve comparable compression ratios, and libdeflate is consistently taking 40-60% of the time that zlib takes.

However, levels 8 and 9 feature significantly worse performance, and the compression ratio increases, not just compared to zlib, but also compared to lower levels of libdeflate.

I wouldn't have thought much of it except for the fact that the performance runs off a cliff at those high levels, enough for me to wonder if there isn't some bug in the code running on those higher levels, and it seems peculiar that the ratio would increase.

The following Callgrind profile indicates that the bulk of the CPU time in my benchmark is being spent in `deflate_compress_near_optimal`:
![image](https://user-images.githubusercontent.com/14214667/95663711-51e5fb00-0b39-11eb-99df-691fbf13015b.png)

OS is Ubuntu 20.04.

Attached are some compression numbers from a quick and dirty impl.
[libdeflate-test.txt](https://github.com/ebiggers/libdeflate/files/5359864/libdeflate-test.txt)

Is this a bug or should I be expecting this kind of behaviour?

**Comment by ebiggers** [comment]
The algorithm changes at level 8 and above.  So that's why there can be a discontinuity between level 7 and 8.  The algorithm at levels 8 and above is slower than the algorithm at levels 7 and below.  However, on most inputs it produces a significantly better compression ratio.  Also, it's usually still slightly faster than zlib.
                                                                                 
Compression is all about heuristics, so it will always be possible to find some inputs where the algorithms don't work as well as expected.  So I'm not sure it's fair to call it a "bug".  But when I have a chance, I'll try to add some more heuristics to improve on this input as well as the input given in https://github.com/ebiggers/libdeflate/issues/57 on which libdeflate also does poorly -- probably something along the lines of dynamically selecting the algorithm and minimum match length based on a quick analysis of the input data.  The file you gave does well with the "lazy" algorithm and a minimum match length of 4 bytes.

**Comment by dktapps** [comment]
Sorry about that, misclicked on my phone ..

**Comment by ebiggers** [comment]
https://github.com/ebiggers/libdeflate/commit/f7d3a70d4c88ceda2fe090a60fae69cb9ef7ef64 fixed this by changing the algorithm used at levels 8 and 9.  Other commits made other improvements to the compression algorithms as well.

Here are the results of DEFLATE compression on `required_block_states.nbt`.  Note: level 10 is the odd one out now (worse than level 9), but not by very much.  It's hard to handle this file perfectly, as it's a bit unusual.

Algorithm | Compressed size | Compression time (ms)
----------|-----------------|----------------------
libdeflate (new) -1 | 118528 | 3
libdeflate (new) -2 | 106640 | 3
libdeflate (new) -3 | 99915 | 3
libdeflate (new) -4 | 92241 | 3
libdeflate (new) -5 | 91444 | 4
libdeflate (new) -6 | 81281 | 5
libdeflate (new) -7 | 74085 | 8
libdeflate (new) -8 | 71513 | 16
libdeflate (new) -9 | 70995 | 21
libdeflate (new) -10 | 72525 | 92
libdeflate (new) -11 | 69871 | 184
libdeflate (new) -12 | 68442 | 396

Here are the results with the old version:

Algorithm | Compressed size | Compression time (ms)
----------|-----------------|----------------------
libdeflate (old) -1 | 119349 | 3
libdeflate (old) -2 | 107242 | 3
libdeflate (old) -3 | 100406 | 3
libdeflate (old) -4 | 93719 | 3
libdeflate (old) -5 | 90841 | 4
libdeflate (old) -6 | 80877 | 5
libdeflate (old) -7 | 74058 | 8
libdeflate (old) -8 | 91419 | 35
libdeflate (old) -9 | 88240 | 46
libdeflate (old) -10 | 77829 | 71
libdeflate (old) -11 | 72562 | 114
libdeflate (old) -12 | 70696 | 189

And with zlib:

Algorithm | Compressed size | Compression time (ms)
----------|-----------------|----------------------
zlib -1 | 118729 | 3
zlib -2 | 110383 | 3
zlib -3 | 102669 | 4
zlib -4 | 97863 | 6
zlib -5 | 90502 | 6
zlib -6 | 74639 | 10
zlib -7 | 73230 | 12
zlib -8 | 71121 | 21
zlib -9 | 71129 | 23
