### ISSUE TITLE
level 0 fake compression not supported

### ISSUE THREAD

**Issue by dktapps** [ebiggers/libdeflate#86]
zlib supports a zero-compression mode under which the data is encapsulated uncompressed. libdeflate appears not to support this and segfaults when 0 is given as compression level.

**Comment by ebiggers** [comment]
Do you have a particular use case in mind for this?  Just because zlib supports it doesn't necessarily mean it is useful.

Also FWIW, `libdeflate_alloc_compressor()` returns `NULL` when given an invalid compression level, i.e. 0, a negative number, or a number over 12.  So if you are seeing a segfault, it's because your code isn't checking for `NULL`.  (Looks like I forgot to document that failure case in `libdeflate.h`; I'll add it.)

**Comment by dktapps** [comment]
In some places a zlib-wrapped stream is required even though we know the data can't be compressed effectively. This is in the context of a Minecraft Bedrock server, where the protocol unconditionally requires deflate-formatted data, although we may choose not to compress depending on the data.

From my experimentation I see that libdeflate already automatically chooses to not bother compressing in some cases, so this shouldn't be too difficult to expose as a level 0.

**Comment by dktapps** [comment]
I guess this is more or less the same as #67 , although the way this is done in classic zlib world is letting the user provide a level 0 for compression.

**Comment by ebiggers** [comment]
Done in https://github.com/ebiggers/libdeflate/pull/88.

**Comment by dktapps** [comment]
Thank you!
